### ISSUE TITLE
Banner color changer doesn't work on 6.0

### ISSUE THREAD

**Issue by dgordonatec** [electriccommunity/EC-Admin#38] opened 2015-07-31 02:50 UTC
Reported by Urban Science. Banner color changer changes new icon back to old icon, but no longer changes the banner color on Flow 6.0.

**Comment by lrochette** [comment] 2015-08-14 13:47
Issue fixed in version 2.10.0.300
The cause was that the .css involved had changed location

**Closed by lrochette** 2015-08-14 13:47 UTC
